### ISSUE TITLE
FEATURE REQUEST: Add a possibility to configure the script to listen in a specified Discord channel

### ISSUE THREAD

**Issue by Varrkan82** [Yoshi-E/Python-BEC-RCon#2]
This will allow to run a few separate copies of a script to manage a different servers by ignoring command from not allowed channel. And to use for this only one Discord bot.

**Comment by Yoshi-E** [comment]
Added in standalone release 1.0 (https://github.com/Yoshi-E/ArmaRconDiscordBot)
You can just remove the bots permission to listen to specific channels in Discords permissions.
Alternatively you can use the following setting:

Can be configured in "/modules/core/config.json":
`"listChannels": []` --> Empty, will listen to all channels
`"listChannels": [602204350907154432]` --> will listen to  to channel with ID 602204350907154432
The only exception is the command "!help". that needs to be disabled manually (In bot.py `pm_help=True` -->`pm_help=False`  )
